# Generated by Django 5.2 on 2025-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Value',
        ),
        migrations.AddField(
            model_name='user',
            name='value',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
