# Generated by Django 5.2 on 2025-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0002_remove_user_value_user_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
